[metadata]
name = nonengine
version = 1.11.0
url = https://github.com/rayanalysis/nonengine/
description = nonengine is a stripped-down PC game engine which supports PBR IBL rendering in an elegant and minimal package.
license = 3-Clause BSD NON-AI License
license_file = new_license.txt
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Intended Audience :: End Users/Desktop
    Operating System :: OS Independent
    Programming Language :: C++
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: Implementation :: CPython
    Topic :: Games/Entertainment
    Topic :: Multimedia
    Topic :: Multimedia :: Graphics
    Topic :: Multimedia :: Graphics :: 3D Rendering
    Topic :: Software Development :: Libraries
    Topic :: Software Development :: Libraries :: Application Frameworks
    Topic :: Software Development :: Libraries :: Python Modules
author = Logan Bier
author_email = loganbierdev@gmail.com
project_urls =
    Source=https://github.com/rayanalysis/nonengine/
