[metadata]
name = nonengine
version = 1.12.0
url = https://github.com/nonengine/nonengine
description = nonengine is a minimal PBR IBL engine descended from Panda3D.
license = BSD-3-Clause and 3-Clause BSD NON-AI License
license_files =
    new_license.txt
    original_Panda3D_license.txt
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Intended Audience :: End Users/Desktop
    Operating System :: OS Independent
    Programming Language :: C++
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: Implementation :: CPython
    Topic :: Games/Entertainment
    Topic :: Multimedia
    Topic :: Multimedia :: Graphics
    Topic :: Multimedia :: Graphics :: 3D Rendering
    Topic :: Software Development :: Libraries
    Topic :: Software Development :: Libraries :: Application Frameworks
    Topic :: Software Development :: Libraries :: Python Modules
author = Logan Bier and Panda3D Team
author_email = loganbierdev@gmail.com
project_urls =
    Home=https://github.com/nonengine/nonengine/
